spring.application.name=tms-server
spring.docker.compose.enabled=false

# Server role configuration - determines if this instance runs scheduled jobs
# Values: MAIN (runs jobs), CONSUMER (skips jobs)
#server.role=MAIN
server.role=CONSUMER


#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
#spring.datasource.username=tms_user
#spring.datasource.password=oracle123
#spring.jpa.hibernate.ddl-auto=validate
#spring.datasource.driver.class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@api4sem_high?TNS_ADMIN=./wallet
spring.datasource.username=ADMIN
spring.datasource.password=Steamducks123@
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
